### ISSUE TITLE
Lang specific searchable attribute

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1219]
For instance:

https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/uvek.py#L1364

**Comment by cedricmoullet** [comment]
@loicgasser what are the next steps here ?

**Comment by procrastinatio** [comment]
It would be nice to add a bit of context to the issue, otherwise, when rewewing, you have to figure out what is the problem, why it is a problem, additionnally to how this is solved

Searching for `galleria`in `description_it`: [7 items](http://api3.geo.admin.ch/rest/services/ech/MapServer/find?layer=ch.bav.sachplan-infrastruktur-schiene_ausgangslage&searchText=galleria&searchField=description_it&returnGeometry=false)

Searching for `tunnel`in `description_it`: [no items](http://api3.geo.admin.ch/rest/services/ech/MapServer/find?layer=ch.bav.sachplan-infrastruktur-schiene_ausgangslage&searchText=galleria&searchField=description_it&returnGeometry=false)

If I undesertand correctly, the goal is to use a neutral fiedl `description` (instead of `description_it`, `descriptions_de`,etc.) and to use the `lang`parameter ?

**Comment by loicgasser** [comment]
The goal is to retrieve only the labels that correspond to the correct lang. With a fallback on `fr` for it, and `de` for `en` and `rm` if the corresponding label does not exist.

Open PR here https://github.com/geoadmin/mf-chsdi3/pull/1277

It should not affect the behavior of the find service.

It is only for the query tool. (featureAttributes -> to retrieve the correct list of attributes and avoid duplicated translated lables)

See https://github.com/geoadmin/mf-chsdi3/blob/gal_lang_spec_attr/chsdi/views/layers.py#L126
