### ISSUE TITLE
500 error on htmlPopup

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1613]
http://api3.geo.admin.ch/1439987023/rest/services/gewiss/MapServer/ch.bafu.typisierung-fliessgewaesser/53502/htmlPopup?coord=710036.3326100261,197316.0993199869&imageDisplay=1920,1075,96&lang=de&mapExtent=708120.3326100261,196302.0993199869,711960.3326100261,198452.0993199869

**Comment by loicgasser** [comment]
solved with https://github.com/geoadmin/mf-chsdi3/pull/1612

**Comment by loicgasser** [comment]
It now return 404

**Comment by gjn** [comment]
This is a different kind of error which is not solved with #1612. Looks like buggy mako to me:

```
Traceback (most recent call last):
  File "/home/ltjeg/mf-chsdi3/buildout/eggs/pyramid_mako-1.0.2-py2.7.egg/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/ltjeg/mf-chsdi3/buildout/eggs/Mako-1.0.0-py2.7.egg/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/home/ltjeg/mf-chsdi3/buildout/eggs/Mako-1.0.0-py2.7.egg/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/ltjeg/mf-chsdi3/buildout/eggs/Mako-1.0.0-py2.7.egg/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/ltjeg/mf-chsdi3/buildout/eggs/Mako-1.0.0-py2.7.egg/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/ltjeg/mf-chsdi3/chsdi/templates/htmlpopup/base.mako", line 68, in render_body
    ${self.table_body(c, lang)}
  File "/home/ltjeg/mf-chsdi3/chsdi/templates/htmlpopup/fliessgewaesser_typ.mako", line 13, in render_table_body
    <%
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by loicgasser** [comment]
Mmm bad copy paste.

**Comment by gjn** [comment]
We get these kind of errors on a regular basis. A mako that doesn't work for _some_ elements in the db. In our unittests, we only are checking the mako for one element.

Doing the tests for all makos and all elements would hit the db quite heavily and would probably take ages. So it's probably not worth it. Maybe it would make sense to check for x elements instead of just 1 (x could be up to 100 or 1000) to increase likelihood of finding a potential error early.

But what is need IMO is that at the end of an integration (or adaption to model/mako), we are able to run sa full tests (test mako with all elements) by hand in the console.

@AFoletti @loicgasser @alcapat @ltclm Thoughts?

**Comment by loicgasser** [comment]
Put the right links once and for all in DB...
Links are updated only when we have a layer update.

**Comment by gjn** [comment]
it's not only about those links. In general, we find mako errors on a regular basis.

regarding the dav0 links: I can see reasons why we check for existence live. Our clients can update data without us needing to update anything.

**Comment by loicgasser** [comment]
In this case sometimes we have link and sometimes we don't.
I am sorry but if we have a link to a resource it should exist...
Here we have to test:

1. that the field is not 2 null
2. that the resource exists

regarding the dav0 links: I can see reasons why we check for existence live. Our clients can update data without us needing to update anything.

In that case it's not true because links are stored in DB..

**Comment by loicgasser** [comment]
At least that's what is implying this mako...

**Comment by gjn** [comment]
Yes, if the links follow a certain pattern, there's no need to put them into the DB, but instead use this pattern in the mako directly. But maybe the client delivered the list of links, being fully aware that not everything exists yet. The data integrator should know this.

But no matter what we do, the main point is that we need to be much more careful when creating our makos'. They need to be more robust.

**Comment by loicgasser** [comment]
Agree

**Comment by loicgasser** [comment]
Knowing if a column is nullable or not would be a good start.

**Comment by gjn** [comment]
+1
