### ISSUE TITLE
Opaque layer property

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-chsdi3#1821]
I put this up for debate.

For 3D currently, we declare some layers as `opaque` [1]. When true, this means that this specific layer hide everything below them _when_ their opacity is 1.0. It's purely informational without any direct technical or visual implications.

I think we should have this information for every layer that we integrate. It will reduce traffice in 3D and can eventually be applied in 3D as well. [2]

@ltclm @AFoletti Do you think it makes sense to track this during the DI process?

[1] list of 3D opaque layers
[2] We have other properties that might be handy: like per zoome level extents (what @loicgasser did for 3D) or full extent of layer (switzerland border or beyond switzerland border.

**Comment by davidoesch** [comment]
+1 cc @mariokeusen

**Comment by ltclm** [comment]
Hello
Actually only 2 layers are 100% opaque, they are hiding ALL other layers in the bgdi due to their extent (in all zoomlevels):
* ch.swisstopo.pixelkarte-farbe-pk1000.noscale
* ch.swisstopo.swissimage (base layer)

``Opaque`` is not a layer property in my eyes, it is a property of a combination of this layer with  all other layers in the bgdi. So theoretically this property has to be updated with each layer integration for every layer. Eventually one day we will integrate a layer with a bigger extent than the two layers above, so they would not be opaque anymore. So this property is not stable and not strictly related to one single layer.
