### ISSUE TITLE
Topic keywords in GeoCat

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1879]
Apparently we now have a topic entry in GeoCat with associated keywords.

It would be nice to have this data since it is useful for topic search.
See: https://github.com/geoadmin/mf-geoadmin3/issues/1666#issuecomment-178520713

@ltclm @AFoletti Once this has been done for the topics we'll probably need to put this info in the BOD.

**Comment by AFoletti** [comment]
yeah, keywords in geocat.
A keyword table is already there. Should not be too much trouble implementing the import

**Comment by loicgasser** [comment]
@mariokeusen Is that something you've planned to do?

**Comment by mariokeusen** [comment]
No, it was never planned or a "must" to have a geocat-entry per topic. May be better and faster to define some keywords per topic outside geocat and without customer interaction. Or what is exactly the goal here, @davidoesch ?

**Comment by loicgasser** [comment]
May be better and faster to define some keywords per topic outside geocat and without customer interaction.

What's the goal of having this capability then?

**Comment by davidoesch** [comment]
" topic entry in GeoCat with associated keywords" ??? who's idea was this?

in gm03 geocat and the BGDITemplate is only the possibility to enter "keywords" not a "topic " per se,
Topics are not configured in geocat. it is purely for mf-geoadmin . on the first thought it makes sense to use a keyword in geocat for topic definition . But I wouldn't since the dataowner has control over it and he can break a topic with this
-> can you show me the corresponing geocat URL where we have such an entry?

**Comment by ltclm** [comment]
my thoughts:
topic should inherit the layer tags which are in this topic. We should ask the data owners to tag their layers and import these tags into the bod layer configuration. If needed we can add ourselves some extra tags for the topics.

**Comment by davidoesch** [comment]
Again: the topic is mf-geoadmin specific. We are planning to adapt the keywords during the data integration process. So: what is the idea behind the topic in geocat?  TBD @mariokeusen

**Comment by loicgasser** [comment]
Lack of activity and probably not the best place to discuss this.
