### ISSUE TITLE
Create tilematrixset factory using gatilegrid

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#1956]
We can get rid of a lot of templates by simply using gatilegrid module and a single
mako template for tileMatrixSet.
https://github.com/geoadmin/mf-chsdi3/tree/master/chsdi/templates/wmtscapabilities

**Comment by loicgasser** [comment]
once https://github.com/geoadmin/mf-chsdi3/pull/1980
@rfrancel you think you can do it?

**Comment by rfrancel** [comment]
Yes I'll have a look!

**Comment by rfrancel** [comment]
@loicgasser the file is factorized using gagridtile.
The scales (calculated with a dpi 90.7) are a little bit different than those currently online, probably because the precision was a little bit different. I let you assess if you think I need to use another dpi.
test link:
http://mf-chsdi3.dev.bgdi.ch/frr_tilematrixset/rest/services/api/1.0.0/WMTSCapabilities.xml

**Comment by gjn** [comment]
Can we have a sample diff of the different outout compared to master?

**Comment by procrastinatio** [comment]
This one can be closed, from my point of view.
