### ISSUE TITLE
ch.bazl.luftfahrtkarten-icao should not be queryable

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2039]
@AFoletti @alcapat 

According to the current set up in geoadmin this layer should not be queryable but it seems this has changed in DB since the daily Jenkins tests fail because of 

======================================================================
FAIL: Failure: AssertionError (ch.bazl.luftfahrtkarten-icao)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<https://jenkins.prod.bgdi.ch/job/chsdi3/ws/.venv/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py",> line 251, in generate
    for test in g():
  File "<https://jenkins.prod.bgdi.ch/job/chsdi3/ws/chsdi/tests/integration/test_layers.py",> line 111, in test_all_htmlpopups
    for layer, feature, extended in lc.ilayersWithFeatures():
  File "<https://jenkins.prod.bgdi.ch/job/chsdi3/ws/chsdi/tests/integration/test_layers.py",> line 57, in ilayersWithFeatures
    assert (models is not None and len(models) > 0), layer
AssertionError: ch.bazl.luftfahrtkarten-icao

Can you guys check what's the deal here?

**Comment by rfrancel** [comment]
No it will be queryable from next week. This error won’t show after the merge of my PR (#2036)

De : Gasser Loïc [mailto:notifications@github.com]
Envoyé : jeudi 21 avril 2016 08:45
À : geoadmin/mf-chsdi3 <mf-chsdi3@noreply.github.com>
Objet : [geoadmin/mf-chsdi3] ch.bazl.luftfahrtkarten-icao should not be queryable (#2039)


@AFoletti<https://github.com/AFoletti> @alcapat<https://github.com/alcapat>

According to the current set up in geoadmin this layer should not be queryable but it seems this has changed in DB since the daily Jenkins tests fail because of

FAIL: Failure: AssertionError (ch.bazl.luftfahrtkarten-icao)

Traceback (most recent call last):
File " line 251, in generate
for test in g():
File " line 111, in test_all_htmlpopups
for layer, feature, extended in lc.ilayersWithFeatures():
File " line 57, in ilayersWithFeatures
assert (models is not None and len(models) > 0), layer
AssertionError: ch.bazl.luftfahrtkarten-icao

Can you guys check what's the deal here?

**Comment by gjn** [comment]
This shouldn't be a problem anymore once the new bod dev process is established. I'll close it as I assume the PR mentioned is close to being merged (need some adaptions still)
