### ISSUE TITLE
Identify on swissimage product returns always esrijson 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2086]
https://mf-chsdi3.dev.bgdi.ch/ltteo/rest/services/ech/MapServer/identify?geometry=633000,215250&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1326,931,96&layers=all:ch.swisstopo.swissimage-product&mapExtent=328500,-42750,991500,422750&returnGeometry=false&tolerance=10

**Comment by procrastinatio** [comment]
Request with returnGeometry=true [linki](https://mf-chsdi3.dev.bgdi.ch/ltteo/rest/services/ech/MapServer/identify?geometry=633000,215250&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1326,931,96&layers=all:ch.swisstopo.swissimage-product&mapExtent=328500,-42750,991500,422750&returnGeometry=true&tolerance=10)

Attributes in properties list, as : 
```
properties: {
title_de: "SWISSIMAGE Level1",
title_en: "SWISSIMAGE Level1",
label: 7,
title_it: "SWISSIMAGE Level 1",
resolution: 0.25,
title_fr: "SWISSIMAGE Level1"
},
 ```

otherwise as `attributes`  [link](https://mf-chsdi3.dev.bgdi.ch/ltteo/rest/services/ech/MapServer/identify?geometry=633000,215250&geometryFormat=geojson&geometryType=esriGeometryPoint&imageDisplay=1326,931,96&layers=all:ch.swisstopo.swissimage-product&mapExtent=328500,-42750,991500,422750&returnGeometry=false&tolerance=10):

```
`attributes`: {
title_de: "SWISSIMAGE Level1",
title_en: "SWISSIMAGE Level1",
label: 7,
title_it: "SWISSIMAGE Level 1",
resolution: 0.25,
title_fr: "SWISSIMAGE Level1"
},
```

So be consequent...
