### ISSUE TITLE
Spatial Reference System in feature resource output

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2150]
What about having the SRS in the feature resource output?

**Comment by davidoesch** [comment]
Is there any other agency /service which this is done?

**Comment by p1d1d1** [comment]
How can users understand which SRS is used?
How can someone easily mashup with e.g. a leaflet.js
Do you see problems? Or do you have examples that don't do that?

Just for discussing

**Comment by davidoesch** [comment]
I see your point, but IMHO the SRS used should be in a GetCap ...

**Comment by procrastinatio** [comment]
Yes, at one point in the future we will have a mix of `LV03` and `LV95`

**Comment by davidoesch** [comment]
this _has_ to be part of the global lv03-lv95 migration strategy.. .

**Comment by procrastinatio** [comment]
According to [ech-0056 v3](http://www.ech.ch/vechweb/page?p=dossier&documentNumber=eCH-0056&documentVersion=3.0), **CRS-01**, it has to be done

**Comment by davidoesch** [comment]
Yep... Today updated. Then go for it

**Comment by p1d1d1** [comment]
@procrastinatio a request specifying the geometry type, e.g. ?geometryFormat=geojson, does not contain the SRS information. 
Don't know if we can have it in GeoJSON: according to this https://tools.ietf.org/html/rfc7946#page-26 the "crs" is no more available in the GeoJSON specs.

**Comment by procrastinatio** [comment]
Like `KML`, `GeoJSON`will be `EPSG:4326` only  (see latest IETF GeoJSON draft.

So, either use something supporting LV95, like `ESRIJson`or `GML`, or completly ditch this LV95 thingy. WGS1984 to anything else, without any date information is a joke for high precision. For the record, the Atlantic Ocean widens up at the speed of 3-4 cm per year (about 1 meter since inception if I am correct).

 I  was trained as a geologist, not as an **ayatollah of the decimal**...

**Comment by davidoesch** [comment]
I close this... can be reopened as soon we have a user stating such a need
