### ISSUE TITLE
Get staging dependent versions of services via parameter

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2299]
Because we need to cache the layersConfig and topics services for geoadmin (and mapproxy), we always need to deploy CHSDI first to access the productive configuration of these services. This is a source of errors and reduces our flexibility in general. (for instance with the activate mechanism in geoadmin)

My proposition is as follow when deploying a snapshot **ONLY** to integration, we should have the final productive state of the application and not something in between.
If we are able to get those config right when deploying to integration, we would have a perfect copy of production state.
This could be handled via parameter.
With a one liner pr this could be addressed in chsdi.
See:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/lib/validation/__init__.py#L26
@gjn thoughts

**Comment by loicgasser** [comment]
If we go this way, we should consider caching all metadata services in S3 bucket.

**Comment by gjn** [comment]
We had exactly that until August 18th. The we changed it. See https://github.com/geoadmin/mf-chsdi3/commit/ad3e373460e1126c5ae4b28b9f9475ed88f90b80#diff-71610ca151165b33aa40aae226038574

We reverted to have int on int because of emapis and because in future, integration platform will be used as Abnahmeplatform. So either we have yet another staging for those uses cases (emapis, Abnahmeplatform) or we find another solution. For a quick solution, I could imagine a geodata_staging=prod parameter for _all_ chsdi3 services that would overwrite the staging defined in production.ini, which would allow to access productive configurations on integration (to create mapproxy config, layersConfig cache, etc). I'd prefer such a paremeter over yet another staging. What do you think?

Currently, our solutions for cached stuff (layersConfig, topics, *.po files, mapproxy config) is sub-optpimal. Those should live update when the source changes. Not easy. Caching is quite complicated business. So I would avoid all caches that are not absolutely needed.

In general, I agree that our deployment process is not optimal. Too many things happen between integration and production. In my vision, we would have prod A and prod B stacks in parallel. While the A stack is active, the B stack would be deployed to and tested. Once tested, the switch would happen on DNS level (or ELB level). Long way to go.

**Comment by loicgasser** [comment]
> I could imagine a geodata_staging=prod parameter for all chsdi3 services that would overwrite the staging defined in production.ini

Yes that's more or less what I had in mind. So geodata_staging=prod should be configured in geoadmin for when deploying to int?

> we would have prod A and prod B stacks in parallel. 

Yes that would be ideal. Keep integration for Abnahmeplatform and stable testing.

**Comment by gjn** [comment]
Yes, you would add `geodata_staging=prod` to the request here: https://github.com/geoadmin/mf-geoadmin3/blob/master/Makefile#L416

Mapproxy would do the same.

Per default, the geodata_staging would be int (because of the other use cases).

**Comment by loicgasser** [comment]
+1

But we may need to brainstorm IRL it a little before taking this decision as I see other potential use cases where this would be problematic. tomorrow or when we have time

**Comment by gjn** [comment]
Yes, agree.

**Comment by procrastinatio** [comment]
This has be done in `mf-geoamin3` (mostly in PR https://github.com/geoadmin/mf-geoadmin3/pull/4792, and https://github.com/geoadmin/mf-chsdi3/pull/3121)
With the new `config_url` param, you may use any config from any environment/branches.

So, we may close this one.
