### ISSUE TITLE
Issue with Luftbilder

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-chsdi3#2484]
We are getting several messages form helpdesk about not available images.
E.g.: ch.swisstopo.lubis-luftbilder_schwarzweiss, 
* go here https://s.geo.admin.ch/71d8c0fcd4 
* click on the icon 82 --> Keine weiteren Informationen. Actually at this point there is no image in 1982, infact:
* select 1982 in layer --> the icon disappears. What remains is working, meaning that the temporal filter is working and showing actual existing data

**Comment by AFoletti** [comment]
see [JIRA](https://jira.swisstopo.ch/browse/BGDIDI_KB-1102) too

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/issues/2485

**Comment by gjn** [comment]
This process has always been like that for lubis (create tiles first, deploy db later), and it has been treated like this for several updates already. So this issue is not new.

For the next update, we will firstdeploy the db and then create the tiles, so there won't be any objects that don't have tooltip.

Now, @loicgasser will deploy the lubis db and this issue will be solved.

**Comment by ltclm** [comment]
The geometry of the data table has been fixed and the tiles have been re-generated.

**Comment by loicgasser** [comment]
Great !

**Comment by p1d1d1** [comment]
everything seems fixed to me. thanks
