### ISSUE TITLE
too many db connections

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2805]
our db slaves have a limit of 300 db connections.
https://metrics.bgdi.ch/main/#/dashboard/db/pg_prod_slaves
![image](https://user-images.githubusercontent.com/5286659/35447651-8ccccea6-02b8-11e8-8170-4707e13dadc0.png)
![image](https://user-images.githubusercontent.com/5286659/35448721-62b71204-02bb-11e8-8146-1d02181ec659.png)

this limit is regularly exceeded.
The number of open connections per database:
```
         datname         | usename  | state  | count
-------------------------+----------+--------+-------
 bod_prod                | www-data | idle   |    88
 kogis_prod              | www-data | idle   |    53
 stopo_prod              | www-data | idle   |    28
 uvek_prod               | www-data | idle   |    26
 lubis_prod              | www-data | idle   |    18
 are_prod                | www-data | idle   |    17
 bafu_prod               | www-data | idle   |    13
 mogis_prod              | www-data | idle   |     8
 uvek_solarkataster_prod | www-data | idle   |     7
 zeitreihen_prod         | www-data | idle   |     6
 dritte_prod             | www-data | idle   |     4
 vbs_prod                | www-data | idle   |     4
 edi_prod                | www-data | idle   |     3
 stopo_prod              | collectd | idle   |     1
 evd_prod                | collectd | idle   |     1
 evd_prod                | www-data | idle   |     1
 bak_prod                | collectd | idle   |     1
 toposhop_prod           | collectd | idle   |     1
 are_prod                | collectd | idle   |     1
 mogis_prod              | collectd | idle   |     1
 kogis_prod              | collectd | idle   |     1
 uvek_solarkataster_prod | collectd | idle   |     1
 postgres                | postgres | active |     1
 edi_prod                | collectd | idle   |     1
 template1               | collectd | idle   |     1
 uvek_prod               | collectd | idle   |     1
 dritte_prod             | collectd | idle   |     1
 efd_prod                | collectd | idle   |     1
 zeitreihen_prod         | collectd | idle   |     1
 bafu_prod               | collectd | idle   |     1
 lubis_prod              | collectd | idle   |     1
 vbs_prod                | collectd | idle   |     1
 bod_prod                | collectd | idle   |     1
(33 rows)
```
i think chsdi is opening too many connections.
https://github.com/geoadmin/mf-chsdi3/blob/516ec31a9c9ee17cebf502f844c330715c46098a/chsdi/models/__init__.py#L24
do we really need this parameter with postgres backend?
http://docs.sqlalchemy.org/en/latest/core/pooling.html#setting-pool-recycle
we should try to improve this.

**Comment by loicgasser** [comment]
I think that we need to recycle the connection to the DB, 20 sec is even a bit small.
Can we increase the number of connections? Looking at the load it's small, we could make them work a bit more.
chsdi is also not the only application connecting to the DB. We'll have to analyze.

**Comment by gjn** [comment]
We have 15 db's defined, a pool_size of 20 for each. We multiply that by the number of instances mf-chsdi3 runs on...

Maybe try to reduce pool_size? Or at least have pool_size different per db (wie have same number for bod as we have for uvek_solarkataster...)

We should try to tweak on mf-chsdi3 level. Let's keep this open as prio 1.

**Comment by loicgasser** [comment]
https://kibana.bgdi.ch/goto/7107bbd11c6b4e4dc287944c694d4e63
From
`gpdb.hc-test.health-connect.ch` a bunch of find requests.

**Comment by loicgasser** [comment]
some explanations about parameters of `create_engine`

See [SQLAlchemy DOC](http://docs.sqlalchemy.org/en/latest/core/pooling.html#setting-pool-recycle)

`pool_size`
All SQLAlchemy pool implementations have in common that none of them “pre create” connections.
The pool would only grow to that size if the application actually used 20 connections concurrently,

`pool_recycle`
If set to non -1, number of seconds between connection recycling, which means upon checkout (give me this DB connection), if this timeout is surpassed the connection will be closed and replaced with a newly opened connection

but we could reduce the pool_size and use the `max_overflow` setting so that DB connections with for instance:
`pool_size=10` and `max_overflow=10` this way extra db connections would be discarded faster after a peak.

Other solutions can be found in CHSDI code. 
All htmlpopup requests involve a DB connection to the BOD to retrieve the full layer name and the attribution.
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/views/features.py#L107

We could build the attribution using a layer prefix (if always the case) and use the translations.

Which is then used here:
https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/templates/htmlpopup/base.mako#L45

Note that we don't have the `fullName` (which is the `bezeichnung` in dataset) in the translations yet.
we only have the `name` or `kurzbezeichnung`

https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/bod.py#L17

So we need to use a convention to put all `fullNames` in the translations and we can avoid opening a connection to the BOD. That would help I think.

ping @ltclm @gjn 

Now I would also like to know if we can increase this limit on the slaves, as I think it's rather low.

How did we choose this number? Who did it? 

A combination of all the measures above should solve this issue.

**Comment by ltclm** [comment]
there seems to be an intense use of the find service with layer ch.bfs.gebaeude_wohnungs_register:
https://kibana.bgdi.ch/goto/1e0c2a495c0c31abb460364f6bdb9223
this makes the number of db connection on kogis rise significantly:
https://metrics.bgdi.ch/main/#dashboard/temp/AWFCe9Jgt6tApkwkuTxr
you can select the database in this dashboard

**Comment by loicgasser** [comment]
here is proposal to put all the full transations in the `po`
DB mig:
https://github.com/geoadmin/tool-wms/compare/autotranslation_fullname?expand=1
CHSDI po:
https://github.com/geoadmin/mf-chsdi3/compare/limit_bodaccess?expand=1

we could prefix it with `fullname.ch.swisstopo.vec200-landcover` for instance.
I can do the same for the attributions and adapt the code in chsdi.

**Comment by ltclm** [comment]
how many connections would mf-chsdi need to open in a worst case scenario on two prod backend with our current wsgi configuration?

**Comment by ltclm** [comment]
our current slaves have 8GB ram and a rotational disk for db data files.
```bash
max_connections                     | 300                                             | Sets the maximum number of concurrent connections.
work_mem                            | 4MB                                             | Sets the maximum memory to be used for query workspaces.
shared_buffers                      | 128MB                                           | Sets the number of shared memory buffers used by the server.
```
according to [1] it should be safe to 
* increase shared_buffers to 25% (2GB) of total ram to avoid slow disk access and load more stuff into memory
* increase max_connections to 600 with a work_mem of 4MB we would use 4.5GB in a worst case scenario with 600 open and active connections

i will apply these changes on the two prod slaves now

[1] https://www.anchor.com.au/hosting/dedicated/Tuning_PostgreSQL_on_your_Dedicated_Server

**Comment by ltclm** [comment]
the settings have been changed on the two prod slaves.

**Comment by ltclm** [comment]
i suggest to monitor how the system behaves now before we start tuning other components.

**Comment by loicgasser** [comment]
+1. Seems like this will boost our DB slaves a lot! Looking at the RAM, CPU and so on I think we are good to go.

**Comment by gjn** [comment]
Let it run for a couple of days with the new 600 limit and then re-evaluate. We need to suffer some peaks first to get an idea.

**Comment by ltclm** [comment]
@gjn @loicgasser 
we had some weak peaks the last couple of days, 
![image](https://user-images.githubusercontent.com/5286659/35846376-b852a094-0b16-11e8-8d6e-be2ebc7017c7.png)

2018-02-02 12:27 -> total db up to 345
2018-02-05 14:40 -> total db up to 330

the database instances are able to handle that much connections without any problems.
see here:
https://metrics.bgdi.ch/main/#/dashboard/db/pg_sandbox_slaves

in the mf-chsdi vhost error logs there are no more errors like this one since 26.01.2018:
```
[Fri Jan 26 21:54:12.517028 2018] [wsgi:error] [pid 13522] [remote 10.220.5.71:14971] OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections
```
so i propose to keep this settings, the same settings have been applied to the sandbox slaves

**Comment by loicgasser** [comment]
+1
sounds like both DB and chsdi are now able to take bigger loads. Thanks a lot
I close, let's reopen if we see more errors like these.

**Comment by gjn** [comment]
Good.
