### ISSUE TITLE
[swisssearch] error in PLZ data

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-chsdi3#3007]
Error message from a geo.admin.ch user:

Usecase: open app, search for PLZ "8260"
Result: "PLZ 8260 - Stein am Rhein (SH, TG)"
Expected result: "PLZ 8260 - Stein am Rhein (SH)", since a commune cannot belong to 2 cantons.
Workaround: request error correction at the data source

Question: which is exactly the source of the PLZ search results. It's obviously not the plzo layer (no such error there). swissboundaries?

**Comment by ltclm** [comment]
in the search service there is a spatial intersection of [1]
* plzo geometry (stopo_master.vd.gabmo_plz.the_geom)
* tlm geometry (stopo_master.tlm.swissboundaries_kantone.the_geom)

since we're intersecting geometries from different tables without any topology with different resolutions, it is possible that there are some slivers and unwanted overlaps.

we would have to set a min area in the intersection query to distinguish between correct overlaps and wrong overlaps. but setting this limit will be a bit difficult. we could try that...

The best would be to ask the (plzo) data owner to add this attribut to the data delivery.


[1] https://github.com/geoadmin/service-sphinxsearch/blob/master/conf/search.conf.part#L286

**Comment by p1d1d1** [comment]
we had the same issue in the past (don't remember which PLZ specifically). 
May I suggest that instead of intersecting polygons, we do a "point in polygon"?
In the PLZ dataset each PLZ has a point associated (ideally to be used as anchor point for the label)

**Comment by p1d1d1** [comment]
That's why I was suggesting to use a point in polygon. The point are (could be) located at the right place.
By the way they already deliver that information, e.g. in the CSV file

**Comment by ltclm** [comment]
yes but the point cannot intersect multiple polygons, we obviously need that for 2108 (Couvet).
So i will try to use the attribute information instead.

**Comment by ltclm** [comment]
cron pr
https://github.com/geoadmin/bgdi-scripts/pull/383

**Comment by ltclm** [comment]
@p1d1d1 you can test the csv attribute based search index here:
https://mf-chsdi3.dev.bgdi.ch/shorten/7dfec2d7e6

**Comment by procrastinatio** [comment]
Without further ado, closing.
