### ISSUE TITLE
Service identify: param `limit` has twice the value

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#3472]
The param `limit` makes the query return twice the number

$ curl -s "https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=42000,30000,900000,350000&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=320,480,96&lang=de&layers=all:ch.bafu.wrz-wildruhezonen_portal&mapExtent=42000,30000,900000,350000&returnGeometry=true&sr=21781&tolerance=0&offset=0&limit=10" | jq -r '.results | length '
20
$ curl -s "https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=42000,30000,900000,350000&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=320,480,96&lang=de&layers=all:ch.bafu.wrz-wildruhezonen_portal&mapExtent=42000,30000,900000,350000&returnGeometry=true&sr=21781&tolerance=0&offset=0&limit=5" | jq -r '.results | length '
10
$ curl -s "https://api3.geo.admin.ch/rest/services/all/MapServer/identify?geometry=42000,30000,900000,350000&geometryFormat=geojson&geometryType=esriGeometryEnvelope&imageDisplay=320,480,96&lang=de&layers=all:ch.bafu.wrz-wildruhezonen_portal&mapExtent=42000,30000,900000,350000&returnGeometry=true&sr=21781&tolerance=0&offset=0&limit=50" | jq -r '.results | length '
100

**Comment by ltkum** [comment]
in chsdi/views/features.py, line 612, we have :      
 `             query = query.limit(flimit) if flimit is not None else query `

we apply the limit to each query, which means we had as many elements as  [number of models for that layer] * [limit parameter] *

And of course, in the general structure it is made so : 
for each layer : 
   ...
   for each model 
        ...
        limit is applied here

if we have 5 layers with two models each, we have 10 time the limit. 

Since the parameter "limit" is not documented in the API, what is the intended function: 
- We apply the limit to each query ? --> we change nothing
- We apply the limit to each layer ? --> what's the expected comportment ? We divide equally between each model ? if the limit is odd, which model gets priority ? If there are more models than there are limits ? 
- We apply the limit globally ? --> same question than for dividing limit between models of a layer, but we add "which layer gets priority ? "

**Comment by ltkum** [comment]
@davidoesch What do you think about this ? Which approach seems to be the "good" one ?

**Comment by boecklic** [comment]
Imho it's an undocumented param, and behaviour has changed since the underlying data has changed it's nothing we should change. The exact same behaviour can as well be desired and expected in other use cases

**Comment by davidoesch** [comment]
I second chris

**Comment by ltkum** [comment]
Sounds good to me, I'll close the issue
